// Code generated by MockGen. DO NOT EDIT.
// Source: ./utils/utils.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockUtils is a mock of Utils interface.
type MockUtils struct {
	ctrl     *gomock.Controller
	recorder *MockUtilsMockRecorder
}

// MockUtilsMockRecorder is the mock recorder for MockUtils.
type MockUtilsMockRecorder struct {
	mock *MockUtils
}

// NewMockUtils creates a new mock instance.
func NewMockUtils(ctrl *gomock.Controller) *MockUtils {
	mock := &MockUtils{ctrl: ctrl}
	mock.recorder = &MockUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUtils) EXPECT() *MockUtilsMockRecorder {
	return m.recorder
}

// TimeNow mocks base method.
func (m *MockUtils) TimeNow() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeNow")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// TimeNow indicates an expected call of TimeNow.
func (mr *MockUtilsMockRecorder) TimeNow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeNow", reflect.TypeOf((*MockUtils)(nil).TimeNow))
}
